### ISSUE TITLE
Default export does not work

### ISSUE THREAD

**Issue by screendriver** [rollup/rollup-plugin-multi-entry#12]
#### rollup.config.js

``` js
import babel from 'rollup-plugin-babel';

export default {
  format: 'cjs',
  entry: 'src/foo.js',
  plugins: [babel()],
  dest: 'dist/bundle.js'
};

```
#### foo.js

``` js
export default 'foo';
```

results in a

``` js
'use strict';

var foo = 'foo';

module.exports = foo;
```

When I use `rollup-plugin-multi-entry` it results in

``` js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });
```

and nothing gets exported.

**Comment by eventualbuddha** [comment]
This is actually an issue in rollup itself (https://github.com/rollup/rollup/issues/840).

**Comment by screendriver** [comment]
Ok. But why it is working with "plain" rollup in my case? It only stops working when I use `rollup-plugin-multi-entry`.

**Comment by TrySound** [comment]
@screendriver Nope, it doesn't work.
http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20*%20from%20'.%2Fmaths.js'%3B%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22export%20default%205%3B%22%7D%5D%7D

**Comment by screendriver** [comment]
@TrySound in my case it [does work](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22const%20foo%20%3D%20'bar'%3B%5Cnexport%20default%20foo%3B%22%7D%5D%7D)
Do the same thing with `rollup-plugin-multi-entry` and it does not work anymore.

**Comment by shellscape** [comment]
@screendriver thanks for opening this issue a while back. we're migrating this plugin to the new plugins monorepo at https://github.com/rollup/plugins. If this issue is still valid, please reopen your issue at the new repo _and please make sure to fill out the appropriate issue template._ We're closing this issue now as part of the migration.
