### ISSUE TITLE
"var"s do not persist across entry files

### ISSUE THREAD

**Issue by mcclure** [rollup/rollup-plugin-multi-entry#13]
Let's say I put this in `js1.js`:

    var x = 3

And this in `js2.js`:

    console.log(x)

And then I make a `rollup.config.js` to build them:

    import multiEntry from 'rollup-plugin-multi-entry';

    export default {
      entry: ['js1.js','js2.js'],
      plugins: [multiEntry()]
    };

This looks good, so I'm gonna go ahead and compile this:

    ./node_modules/.bin/rollup -c rollup.config.js -o js3.js

Here are the final contents of `js3.js`:

    console.log(x)

This program fails when run, because the `var x = 3` from js1.js was just dropped. If I replace `var x = 3` with `x = 3`, the x is included and the program runs.

**Expected behavior**

One way of writing JS code is to write several source files and then effectively concatenate them by saying `<script src="js1.js"/><script src="js2.js" />` in an HTML file or similar. In this case, under browser rules at least, all the files run in one global scope, even if they're `var`s. Currently I am doing this with my JS projects, and it would be actually sort of difficult for me to do otherwise because I am using transpilers. My `js1.js` is generated by TypeScript and my `js2.js` is generated by something called Nim and at this exact moment, TypeScript supports es6 modules but Nim does not.

IMO Rollup should be able to support this use case, and rollup-plugin-multi-entry would be the most sensible vehicle for supporting it. multi-entry should at least have a configuration option for treating inputs as "one long file" and not culling variables until it knows that later entry point files will not be using them. Is this possible? :O

Note: I could sorta get what I wanted by literally running

    cat js1.js js2.js > js3.js

But in this case I don't get sourcemap support, which I really want.

**Comment by sebs** [comment]
So trying this [https://github.com/lydell/source-map-concat](https://github.com/lydell/source-map-concat)

i got me this

```js
/* Bruce Banner */
void function(){
// File: a.js
x = 1;

}();
void function(){
// File: b.js
x = 2;
}();
/* Footer */
```

Makes sense so far and cuts you off from using one global scope as var or avoiding var in that case, means local scope to the function. So there goes your undefined. Declaration and execution in one. **function(){}()**;

You can however, viewer discretion advised, get access to the global scope: use global on node.js and window for browser:

```js
var global = window || global;
global.a = 1;
```

this way you can have access to it. The tool at hand gives you a source map as well. Use this with real care and maybe develop a "contract" under one special window/global variable ($$ or $_$ - just make sure its hard to type on european keyboards ;)

**Comment by sebs** [comment]
> This program fails when run, because the var x = 3 from js1.js was just dropped. If I replace var x = 3 with x = 3, the x is included and the program runs.

I forgot about this: no var means assignment to global scope. [see](http://stackoverflow.com/questions/1470488/what-is-the-purpose-of-the-var-keyword-and-when-to-use-it-or-omit-it)

**Comment by mcclure** [comment]
@sebs: So in my situation I cannot easily alter the code. I didn't write the code. It is the output of a transpiler. I'm trying to wire the output of a transpiler into rollup.

**Comment by eventualbuddha** [comment]
You're misunderstanding how this plugin works. It creates a virtual module that re-exports the exports of the modules listed in the config. They are *not* concatenated in the way you're expecting. You may find a plugin to do exactly what you're looking for, or you could simply write one using magic-string to get source map support.
