### ISSUE TITLE
Entry module cannot be external

### ISSUE THREAD

**Issue by CodeTroopers** [rollup/rollup-plugin-multi-entry#20]
If i want to flag as external all modules not in the src directory with this rollup configuration file
```js
import multiEntry from "rollup-plugin-multi-entry";

export default {
	entry: "tests/**/*.js"
	format: "cjs",
	plugins: [
		multiEntry ()
	],
	external: id => !(/src\//.test(id)),
	dest: "dist/tests.js"
};
```
then rollup fails with 

> Entry module cannot be external

because the entry point is replaced with `rollup-plugin-multi-entry:entry-point` and the external function doesn't match

**Comment by shellscape** [comment]
Closing as related to #21
