### ISSUE TITLE
Does not work with latest rollup.js

### ISSUE THREAD

**Issue by swansontec** [rollup/rollup-plugin-multi-entry#24]
I recently upgraded from rollup.js 0.46.2 to 0.49.2, and rollup-plugin-multi-entry stopped working:

```
src/**/*.test.js → build/tests.cjs.js...
[!] Error: Could not resolve entry (src/**/*.test.js)
Error: Could not resolve entry (src/**/*.test.js)
    at error (/Users/william/airbitz/airbitz-core-js/node_modules/rollup/dist/rollup.js:185:14)
    at resolveId.then.id (/Users/william/airbitz/airbitz-core-js/node_modules/rollup/dist/rollup.js:9552:6)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

Here is my config file:

```js
import multiEntry from 'rollup-plugin-multi-entry'

export default {
  external: ['chai', 'redux'],
  input: 'src/**/*.test.js',
  output: [{ file: 'build/tests.js', format: 'cjs' }],
  plugins: [multiEntry()],
  sourcemap: true
}
```

**Comment by swansontec** [comment]
Ah, I see that there is already pull request about this: #23

**Comment by ronanquillevere** [comment]
would be great to fix this asap :) thx

**Comment by jeremychone** [comment]
Workaround: Took me a little while to trace back the release, but `"rollup": "0.47.6"` has the old naming scheme and work with the current multi-entry.

**Comment by swansontec** [comment]
It looks like a fix has been committed to this plugin (thanks @minasmart), but there is no NPM release that exposes the fix to the world. Somebody just needs to bump the version and do an `npm publish` at this point.

**Comment by yvele** [comment]
I think we have [another related problem](https://github.com/rollup/rollup-plugin-multi-entry/issues/25) when passing input as an array 

> [!] TypeError: Path must be a string.

Is the owner @eventualbuddha not active anymore to publish the PR to npm?

**Comment by eventualbuddha** [comment]
v2.0.2 has been published to npm and *should* work with the latest Rollup. Please comment if not!
